services:
    inu-desktop:
        build: .
        hostname: inu
        ports:
            - 4845:4845/tcp
            - 4845:4845/udp
        volumes:
            - ./mnt:/mnt
        environment:
            WEB_PORT: 4845
            UDP_PORT: 4845
            PUBLIC_IP: 162.233.34.155

            SCREEN_WIDTH: 1920
            SCREEN_HEIGHT: 1080
            FRAMERATE: 60

            # OUTPUT_LOGS: 1
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
